languageCode = "en-us"
title = "SHEPRD"
theme = "hugo-book"
baseURL = "https://hermes-sheprd.netlify.com/"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
BookLogo = 'logo.png'
