---
bookCollapseSection: true
title: Discrete Event Simulation
output: html_document
---

# Discrete Event Simulaltion

## Introduction

“Discrete event simulation (DES) is a computer-modelling technique used in economic evaluation of health interventions in which individual patient experience is simulated over time, and events occurring to the patient and the consequences of such events are tracked and summarised. Unlike cohort Markov models, in DES movements between patients’ health states are usually driven by events which may occur at varying times (rather than during cycles of fixed length), and time-to-event distributions are required for each event.” Taken from Discrete Event Simulation [online]. (2016). York; York Health Economics Consortium; 2016. https://yhec.co.uk/glossary/discrete-event-simulation/ [Accessed 01/04/2020]

See also https://www.ispor.org/docs/default-source/resources/outcomes-research-guidelines-index/modeling_using_discrete_event_simulation-4.pdf?sfvrsn=ef593594_0


## When might I use this?

These models are suited to modelling more complex conditions where there are numerous potential outcomes and events, for example a chronic disease that will have a wide range of different events and complications. Individual patient history and subsequent events impact the event likelihood. There are no fixed discrete time intervals so such models can be more flexible.
DES models can also be used to compare situations of constrained resources.
Some common uses of DES models are for more complex chronic diseases eg. diabetic patients and the multiple outcomes and complications. Constrained resource models might look at things such as hospital wait times and resource allocation.


# Packages
Descriptions to be added here