---
bookCollapseSection: true
title: Parameter Uncertainty and Sensitivty Analysis
output: html_document
---
# Sensitivty Analysis 

## Introduction
Models are used to inform decision making and resource allocation in health care, therefore, it is important that they report point estimates for specific outcomes as well as the uncertainty surrounding these outcomes. Modellers can perform sensitivity analyses (deterministic or probabilistic) to report on the uncertainty of their models’ outcomes, or value of information analysis to assess the expected gain from reducing uncertainty through some form of data collection exercise (trial, epidemiological study, etc.). 

See also: https://www.ispor.org/docs/default-source/resources/outcomes-research-guidelines-index/model_parameter_estimation_and_uncertainty-6.pdf?sfvrsn=8bc10c8e_0) 

## When might I use this?
Sensitivity analyses can be used to incorporate parameter uncertainty into health economic models, allowing for an understanding of parameter-related uncertainty within the 
Deterministic sensitivity analysis is used when we want to see the impact of a specified change in one particular variable on the outcome estimate of out model (e.g. the impact of different drug prices on the incremental cost-effectiveness ratio). See: Deterministic Sensitivity Analysis [online]. (2016). York; York Health Economics Consortium; 2016. https://yhec.co.uk/glossary/deterministic-sensitivity-analysis/ 
Probabilistic sensitivity analysis is used when we want to incorporate parameter uncertainty through pulling from parameter distributions, and we can also simultaneously  do this for multiple parameters in order to give an overall estimate of certainty in the outcome estimate (e.g. incremental cost-effectiveness ratio) in relation to uncertainty surrounding all of the model parameter inputs. See: Probabilistic/Stochastic Sensitivity Analysis [online]. (2016). York; York Health Economics Consortium; 2016. https://yhec.co.uk/glossary/probabilistic-stochastic-sensitivity-analysis/ 

